#! /bin/sh
set -e

NAME=aesdsocket
PIDFILE=/var/run/$NAME.pid
DAEMON=/bin/aesdsocket
DAEMON_OPTS="-d"

case "$1" in
    start)
        echo "Starting simpleserver"
        start-stop-daemon --start --quiet -n $NAME --exec $DAEMON -- $DAEMON_OPTS
        ;;
    stop)
        echo "Stopping simpleserver"
        start-stop-daemon --stop --quiet --oknodo -n $NAME
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0
        